version: "3.8"

services:
  app:
    build: ./
    container_name: crawler_app
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    environment:
      MONGODB_DATA_DIR: /data/db
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodbdata: